version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8013:80"
    volumes:
      - .:/home/dev/app
  db:
    image: mysql:5.7.26
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=podcastfeeder
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/dump:/dump/
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/home/dev/app
  node:
    image: node:12.12.0-buster
    working_dir: /home/dev/app
    #    build: 
    #  context: .
    #  dockerfile: docker/node/Dockerfile
    tty: true
    volumes:
      - .:/home/dev/app
      - /home/dev/app/node_modules
